# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

cirrus_wm_adsp-objs = wm_adsp.o ../../../drivers/firmware/cirrus/cs_dsp.o
obj-m += cirrus_wm_adsp.o

cirrus_cs35l45-objs = cs35l45.o cs35l45-tables.o
obj-m += cirrus_cs35l45.o

ccflags-y := -I $(srctree)/../sm8650-modules/cirrus/kernel-modules/cs35l45/include/

ifneq ($(filter m y,$(CONFIG_SND_SOC_CS35L45_SPI)),)
   cirrus_cs35l45-objs += cs35l45-spi.o
else
   cirrus_cs35l45-objs += cs35l45-i2c.o
endif

